var Dictionary = {
	nouns:[
		"idiot",
		"millennial",
		"boner",
		"mother",
		"penis",
		"expert",
		"webinar",
		"weed",
		"tits",
		"blog",
		"brand",
		"twitter",
		"new york times",
		"valleywag",
		"wife",
		"joke",
		"troll",
		"butt",
		"tumblr",
		"longread",
		"newsweek",
		"sweater",
		"dong",
		"dick",
		"porn",
		"phish",
		"second life",
		"screenshot",
		"potluck",
		"boots",
		"lammer"
	],
	positions:[
		"dad",
		"mom",
		"troll",
		"wife",
		"sister",
		"bro",
		"guy",
		"drug dealer",
		"women",
		"professional",
		"social media editor",
		"curator",
		"DUDE"
	],
	verbs:[
		"fart",
		"twerk",
		"shit",
		"piss",
		"fuck",
		"play",
		"stroke",
		"unfollow",
		"retweet",
		"click",
		"curate",
		"smoke",
		"screenshot",
		"tweet"
	],
	adjectives:[
		"high",
		"horny",
		"gross",
		"anal",
		"dank",
		"bad",
		"nice",
		"fat",
		"cool",
		"moist",
		"gay",
		"dumb",
		"weird",
		"sexy",
		"rich",
		"fun",
		"old",
		"stupid",
		"troll",
		"interracial double-penetration"
	],
	peoples:[
		"buzz aldrin",
		"matthew keys",
		"maria popova",
		"anthony de rosa",
		"anil dash",
		"troll",
		"Roger Ebert",
		"@sweden",
		"mg siegler",
		"michael arrington",
		"tom friedman"
	],
	users:[
		"the_curator",
		"inky",
		"langer",
		"rustyk5",
		"igowen",
		"bp",
		"nostrich",
		"keithc",
		"ckolderup",
		"marco",
		"jessica",
		"fwarg",
		"hilda",
		"lysol",
		"palomar",
		"cubicle17",
		"creature",
		"toxick",
		"Vidar",
		"bengold",
		"foldingcookie",
		"cheerschopper",
		"aberet",
		"nik",
		"nosmo",
		"johnholdun",
		"mwunsch"
	],
	exclamations:[
		"lol",
		"lmao",
		"lmbo",
		"so",
		"oh boy",
		"well",
		"fuckers",
		"FUCK",
		"LOL",
		"HOLY SHIT",
		"OMG",
		"yeah"
	],
	sentences:[
		"{user}: if i was {people} I'd just walk around with my {noun} {verb}ing out all the time because {verb}ing on the moon is basically a license to {verb} {noun} for the rest of your life",
		"{user}: how do you define a {noun} <br /> keith: someone younger than me who is a {noun}",
		"{user}: is {noun} api down? <br /> {user}: ? <br /> {user}: wake up you {adjective} {noun}fuckers <br /> {user}: i hate you all",
		"{user}: im announcing that i'm no longer clicking {user}'s links unless there is some great response in the {noun}",
		"{user}: every {noun} should have at least two {noun}s {verb}ing it",
		"langer: i came out fully formed <br /> langer: i was {user} on the first day of my life <br /> langer: first thing i did after {verb}ing my {position}'s {noun} was {verb} her on Twitter",
		"{user}: hate when i click the wrong link and get some bullshit about {nouns} instead of {noun}",
		"nostrich: god this is actually fun, kill me <br /> nostrich: i don't want to {verb} {noun}s",
		"langer: {exclamation} <br />langer: {exclamation} <br />langer: {exclamation} {exclamation}<br />langer: {exclamation} <br />langer: my {noun}<br />langer: {exclamation}<br />langer: are you ready for this<br />langer: my {noun}<br />langer: it was {verb}ing<br />langer: and i was like<br />langer: {exclamation}<br />{user}: are these {noun} lyrics",
		"[40 minute argument about {noun}s, {noun} trade-offs, and {noun}s]<br />{user}: is anyone in this super cool irc channel going to {noun} club tonight<br />[argument continues unabated]",
		"{user}: this provides some real insight into how fucking {adjective} we all are",
		"igowen: look around you<br />igowen: just look around you<br />igowen: have you worked out what we're looking for?<br />igowen: correct! the answer is: {noun}s",
		"{user}: {people} died<br />{user}: now no one can stop me from making {noun}s into art",
		"{user}: take the {noun} and {verb} it into {noun}",
		"nostrich: you guys are always welcome to take my {noun} for a {verb}<br />nostrich: no {verb} stuff though",
		"{user}: {noun}bake {user} 1967",
		"{user}: i think u know why im here!? {noun}",
		"{user}: who the fuck is {verb}ing {noun} at my {noun}. show yourself, {noun}. i will never {verb}",
		"{user}: i see so many {noun}s today out",
		"{user}: they had a falling out<br />{user}: ({noun} falling out of {noun})",
		"{user}: I only found that {noun} because I happened to be googling '{noun} {verb}'",
		"{user}: attn tumblrs the {noun} has been {verb}ed",
		"{user}: we're white hat {noun}",
		"{user}: The key to winning arguments in tumblrs is to {verb} your {noun} in such a way that people either {verb} or {verb}.",
		"{user}: {people} fuck {noun}<br />{user}: {people} get pragnent<br />{user}: how???",
		"nostrich: guys it is so {adjective} outside today<br />nostrich: {noun} weather is coming!!!<br />nostrich: can't wait",
		"{user}: of course my {position} peeks over my cubicle wall just as i get to a {adjective} {noun} screenshot",
		"{user}: i don't {verb} to look {adjective}, i {verb} to get {adjective}",
		"drazin: hey guys i had a rare good idea<br />{user}: i'll believe it when i {adjective} it<br />drazin: lets do a {adjective} {noun} league<br />igowen: nope<br />igowen: not a good idea",
		"bengold: now i want {noun}s<br />bengold: or maybe i want {noun}s",
		"{user}: it's friday evening guys<br />{user}: i am in {noun} mode<br />{user}: let's {verb} {noun}s!!!",
		"{user}: i am the {position} who {verb}s like a hundred {position}s",
		"{user}: everyone is part of the same {noun} on twitter<br />{user}: you're in a {adjective}, {adjective} {noun} where {position}s and {position}s alike can {verb} {noun} and {verb} the {adjective} {noun}",
		"{user}: ok which one of you just {verb}ed me '{noun}s'",
		"{user}: {noun}'s the new {noun}, {noun} is dead",
		"{user}: dude, go for as long as i have without {noun} and you'll get wood every time you go to {people}'s {noun}",
		"{user}: {people} has won pulitzers, what did you ever do??<br />{user}: i got a {adjective} {noun} once",
		"{user}: Anyone know nice hotels in Paris?<br />{user}: ah, oui, l'hotel du {noun}age<br />{user}: is that {adjective}? the {noun} hotel?",
		"{user}: i wish i could mouse with my {noun}<br />{user}: then i would never leave home row",
		"johnholdun: get more {noun}s<br />johnholdun: how do i get more {noun}s<br />johnholdun: how do you get people to {verb} you on {noun}<br />johnholdun: oops wrong window",
		"{user}: {noun}s, {noun}s--they're all the same on a {adjective} computer",
		"{user}: hi<br />{user}: hi!<br />{user}: hi!!!<br />{user}: {adjective} {noun}<br />{user}: {noun}!<br />{user} left the chat room.",
		"{user}: the onli {adjective} is u whit u {noun} tallk",
		"{user}: terrorists are fucking {adjective}<br />{user}: {verb} some place unexpected, like atlanta",
		"{user}: {user} insulted my {noun}",
		"{user}: ugh {user} learn to {noun} please",
		"langer: I AM NOT A {noun} BLGGR<br />{user}: oh, i just assumed<br />langer: i thought i blogged about {noun}s and {noun}<br>langer: ok<br />langer: glanced at my front page<br />langer: guess i'm a {noun} blogger now<br />langer: fuck my life",
		"{user}: ~ excuse 2 {verb} {noun}s ~",
		"{user}: got my finger right on the pulse of literally anything that is {adjective}",
		"{user}: {people}'s sleeping with me at REDACTED<br />{user}: it's {adjective} because none of you even know I'm actually {noun}"
	]
}